services:
  server-watcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-watcher
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./wathcer_app.db:/app/wathcer_app.db
    environment:
      - TZ=UTC
      - BACKEND_PORT=choose your available port
      - JWT_SECRET=jwt_secret_key
    privileged: true
    pid: host
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"